version: "3.9"

services:
  django:
    image: django-project
    build: ./backend
    container_name: backend_c
    ports:
      - "8000:8000"
  react:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
