version: "3"

services:
  frontend:
    image: habibo1234/hng-front-end:latest
    container_name: frontendpage
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: habibo1234/hng-back-end:latest
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8008
    ports:
      - "8008:8008"
networks:
  default:
  name:
  external:
